"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = true


# WARNING: Managed by `autostyle.lua`
# Colors
[palette]
teal = '#76e3ea'
green = '#3fb950'
mauve = '#bc8cff'
pink = '#f778ba'
red = '#ff7b72'
subtext = '#6e7681'


# Prompt - 'Zero-th' Line
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = false

    [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "p:subtext"
    template = "󱞽 {{ .FormattedMs }}"

        [blocks.segments.properties]
        threshold = 500
        style = "austin"
        always_enabled = true

    [[blocks.segments]]
    type = "status"
    style = "plain"
    template = "{{ if .Error }} [{{ reason .Code }}] {{ end }}\n"
    foreground = "p:subtext"
    foreground_templates = ["{{ if .Error }}p:red{{ end }}"]

        [blocks.segments.properties]
        always_enabled = true


# Prompt - First Line
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

    [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '{{ .UserName }}{{ if .SSHSession }}@{{ index (splitList "." .HostName) 0 }}{{ end }} '
    foreground = 'p:teal'

    [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .Path }} '
    foreground = 'p:pink'

        [blocks.segments.properties]
        folder_icon = '....'
        home_icon = '~'
        style = 'agnoster_short'
        max_depth = 3

    [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = """\
        {{ .HEAD }}\
        {{if .BranchStatus }} {{ .BranchStatus }}{{ end }}\
        {{ if .Working.Changed }}  {{ .Working.String }}{{ end }}\
        {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}\
        """
    foreground = 'p:mauve'

        [blocks.segments.properties]
        branch_icon = ' '
        cherry_pick_icon = ' '
        commit_icon = ' '
        fetch_status = true
        fetch_upstream_icon = false
        merge_icon = ' '
        no_commits_icon = ' '
        rebase_icon = ' '
        revert_icon = ' '
        tag_icon = ' '

    [[blocks.segments]]
    type = 'python'
    style = 'plain'
    template = """ \
        {{ if .Error }}{{ .Error }} {{ else }}\
        {{ if .Venv }}({{ .Venv }}) {{ end }}\
         {{ .Major }}.{{ .Minor }} \
        {{ end }}\
        """
    foreground = 'p:subtext'


# Prompt - Second Line
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

    [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '󱞩'
    foreground = 'p:green'


# Transient Prompt
[transient_prompt]
template = "<p:subtext>󱞽 {{ .Segments.Executiontime.FormattedMs }}{{ .Segments.Status.Text }}</>\n󱞫 "
foreground = 'p:mauve'
